# Generated by Django 3.0.6 on 2020-05-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photo', models.FileField(upload_to='upload/')),
                ('buy_url', models.URLField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Genre')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Media')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Status')),
            ],
        ),
    ]
